src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    use TimestampableEntity;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="У вашей великолепной статьи должен быть такой же заголовок")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $body;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $likeCount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="articles")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }
    
    public function isPublished(): bool
    {
        return null !== $this->getPublishedAt();
    }

    public function getLikeCount(): ?int
    {
        return $this->likeCount;
    }

    public function setLikeCount(?int $likeCount): self
    {
        $this->likeCount = $likeCount;

        return $this;
    }
    
    public function like()
    {
        $this->likeCount++;
        return $this;
    }
    
    public function dislike()
    {
        $this->likeCount--;
        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }
    
    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments;
//        $criteria = Criteria::create()
//            ->andWhere(Criteria::expr()->isNull('deletedAt'))
//            ->orderBy(['createdAt' => 'DESC'])
//        ;
//        return $this->comments->matching($criteria);
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if (mb_stripos($this->getTitle(), 'собак') !== false) {
            $context
                ->buildViolation('Про собак писать запрещено')
                ->atPath('title')
                ->addViolation()
            ;            
        }
    }
}

src/Controller/Admin/ArticlesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Article;
use App\Entity\User;
use App\Form\ArticleFormType;
use App\Repository\ArticleRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @method User|null getUser()
 */
class ArticlesController extends AbstractController
{
    /**
     * @IsGranted("ROLE_ADMIN_ARTICLE")
     * @Route("/admin/articles", name="app_admin_articles")
     */
    public function index(ArticleRepository $articleRepository, Request $request, PaginatorInterface $paginator)
    {
        $pagination = $paginator->paginate(
            $articleRepository->latest(),
            $request->query->getInt('page', 1),
            10
        );
    
        return $this->render('admin/article/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }
    
    /**
     * @IsGranted("ROLE_ADMIN_ARTICLE")
     * @Route("/admin/articles/create", name="app_admin_articles_create")
     */
    public function create(EntityManagerInterface $em, Request $request, FileUploader $articleFileUploader)
    {
        $form = $this->createForm(ArticleFormType::class, new Article());

        if ($article = $this->handleFormRequest($form, $em, $request, $articleFileUploader)) {

            $this->addFlash('flash_message', 'Статья успешно создана');

            return $this->redirectToRoute('app_admin_articles');
        }
        
        return $this->render('admin/article/create.html.twig', [
            'articleForm' => $form->createView(),
            'showError' => $form->isSubmitted(),
        ]);
    }

    /**
     * @Route("/admin/articles/{id}/edit", name="app_admin_article_edit")
     * @IsGranted("MANAGE", subject="article")
     */
    public function edit(Article $article, EntityManagerInterface $em, Request $request, FileUploader $articleFileUploader)
    {
        $form = $this->createForm(ArticleFormType::class, $article, [
            'enable_published_at' => true,
        ]);

        if ($article = $this->handleFormRequest($form, $em, $request, $articleFileUploader)) {

            $this->addFlash('flash_message', 'Статья успешно изменена');

            return $this->redirectToRoute('app_admin_article_edit', [
                'id' => $article->getId(),
            ]);
        }

        return $this->render('admin/article/edit.html.twig', [
            'articleForm' => $form->createView(),
            'showError' => $form->isSubmitted(),
        ]);
    }
    
    private function handleFormRequest(FormInterface $form, EntityManagerInterface $em, Request $request, FileUploader $articleFileUploader)
    {
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Article $article */
            $article = $form->getData();

            /** @var UploadedFile|null $image */
            $image = $form->get('image')->getData();
    
            if ($image) {
                $article->setImageFilename($articleFileUploader->uploadFile($image, $article->getImageFilename()));
            }

            $em->persist($article);
            $em->flush();
            
            return $article;
        }
        
        return null;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;


use App\Entity\Article;
use App\Events\UserRegisteredEvent;
use App\Repository\ArticleRepository;
use App\Service\SlackClient;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     */
    public function homepage(ArticleRepository $repository)
    {
        $articles = $repository->findLatestPublished();

        $banner = rand(0, 1) ? 'images/cat-banner1.jpg' : 'images/cat-banner.jpg';
        
        return $this->render('articles/homepage.html.twig', [
            'articles' => $articles,
            'banner' => $banner,
        ]);
    }

    /**
     * @Route("/articles/{slug}", name="app_article_show")
     */
    public function show(Article $article, SlackClient $slack)
    {
        if ($article->getSlug() === 'slack') {
           $slack->send('Привет, это важное уведомление!');
        }

        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }
}

templates/articles/content.html.twig
{% extends 'base_content.html.twig' %}

{% block title %}Генерация контента статьи{% endblock %}

{% block content_row_class %}{{ parent() }} p-4{% endblock %}
{% block content_col_class %}p-0{% endblock %}

{% block content %}
<h1>Генерация контента статьи</h1>

<form>
    <div class="form-group">
        <label>Количество параграфов</label>
        <input
            type="text"
            class="form-control"
            name="paragraphs"
            value="{{ app.request.query.get('paragraphs') }}"
        >
    </div>
   
    <div class="form-group">
        <label>Вставляемое слово</label>
        <input
            type="text"
            class="form-control"
            name="word"
            value="{{ app.request.query.get('word') }}"
        >
    </div>
    <div class="form-group">
        <label>Количество повторений вставляемого слова</label>
        <input
            type="text"
            class="form-control"
            name="wordsCount"
            value="{{ app.request.query.get('wordsCount') }}"
        >
    </div>
    <button type="submit" class="btn btn-primary">Сгенерировать</button>
</form>

{% if (articleContent) %}
<hr>
<div>{{ articleContent|cached_markdown }}</div>
{% endif %}

{% endblock %}

templates/articles/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">

            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-12 col-md-8">

                        {{ render(controller('App\\Controller\\PartialController::mainBanner', {
                            banner: banner
                        })) }}

                        {% for article in articles %}
                        <div class="article-container mb-2">
                            <div class="row no-gutters border rounded-lg overflow-hidden flex-md-row mb-4 shadow-sm position-relative">
                                <div class="col-auto d-none d-lg-block">
                                    <img class="article-img" src="{{ article.imageFilename | imagine_filter('articles_preview') }}">
                                </div>
                                <a class="col p-2 px-4 d-flex flex-column article-item" href="{{ path('app_article_show', { slug: article.slug}) }}">
                                    <h5 class="mb-2">{{ article.title }} <span class="badge badge-info article-comments">{{ article.nonDeletedComments|length }} комментов</span></h5>
                                    {% include 'partial/article_tags.html.twig' with { tags: article.tags } %}
                                    <div class="d-flex justify-content-between">
                                        <div class="text-muted align-self-center">
                                            <img
                                                class="article-author-img rounded-circle"
                                                src="{{ article.author.avatarUrl }}"
                                            > {{ article.author.firstName }}
                                        </div>
                                        <div class="text-muted align-self-center">{{ article.publishedAt ? article.publishedAt|ago }}</div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <div class="col-sm-12 col-md-4 text-center">
                        <div class="bg-white shadow-sm border rounded-lg pb-2 pt-2 px-5 mb-4 featured-border">
                            <div class="ad-space mx-auto mt-1 pb-2 pt-2">
                                <img class="advertisement-img mb-2" src="{{ asset('images/cat-food.jpg')}}">
                                <p><b>Новинка:</b> Лакомные <i class="fas fa-heart text-warning"></i> <i class="fas fa-heart text-info"></i> <i class="fas fa-heart text-danger"></i></p>
                                <button class="btn btn-info">Купить сейчас</button>
                            </div>
                        </div>

                        {{ render(controller('App\\Controller\\PartialController::catsKnowThis')) }}
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/show.html.twig
{% extends 'base_content.html.twig' %}

{% block title %}Статья: {{ article.title }}{% endblock %}

{% block content_row_class %}{{ parent() }} no-gutters featured-border{% endblock %}
{% block content_col_class %}{{ parent() }} article-detail{% endblock %}

{% block content %}
    <div class="col-sm-12 p-2">
        <div class="media d-flex align-content-center">
            <img class="article-detail-image align-self-start mr-3 rounded" src="{{ article.imageFilename | imagine_filter('articles_detail') }}">
            <div class="media-body d-inline-block align-self-center">
                <h1 class="mb-2">{{ article.title }}</h1>
                {% include 'partial/article_tags.html.twig' with { tags: article.tags } %}
                <div class="d-flex">
                    <div class="text-muted align-self-center">
                        <img
                            class="article-author-img rounded-circle mr-2"
                            src="{{ article.author.avatarUrl }}"
                        >
                        {{ article.author.firstName }}
                    </div>
                    <div class="text-muted align-self-center ml-4">{{ article.publishedAt ? article.publishedAt|ago : 'Неопубликована'}}</div>
                    <div
                        class="text-muted align-self-center ml-4 article-detail-hearts"
                        data-item="likes"
                        data-type="like"
                        data-like-href="{{ path('app_article_like', {slug: article.slug, type: 'like'}) }}"
                        data-dislike-href="{{ path('app_article_like', {slug: article.slug, type: 'dislike'}) }}"
                    ><span data-item="likesCount">{{ article.likeCount }}</span> <i class="far fa-heart text-danger"></i></div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-12 mt-2 mb-4">
        {{ article.body|cached_markdown }}
    </div>


    <div class="col-sm-12 mb-4">
        <h3><i class="pr-3 far fa-comment text-secondary"></i>{{ article.nonDeletedComments|length }} Комментария</h3>
        <hr>

        <div class="row mb-4">
            <div class="col-sm-12">
                <div class="comment-container align-self-start col-sm-6">
                    <div class="form-group">
                        <textarea class="form-control" rows="2"></textarea>
                    </div>
                    <button type="submit" class="btn btn-info">Комментировать</button>
                </div>
            </div>
        </div>

        {% for comment in article.nonDeletedComments %}
            <div class="row mt-2">
                <div class="col-sm-12">
                    <div class="media">
                        <img class="align-self-start comment-img rounded-circle" src="{{ asset('images/cat-profile.png') }}">
                        <div class="media-body align-self-start col-sm-6">
                            <b>{{ comment.authorName }}</b>
                            <small>{{ comment.createdAt|ago }} {% if comment.deletedAt %} DELETED {% endif %}</small>
                            <br>
                            <span class="comment">{{ comment.content }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}